### ISSUE TITLE
External RDS decoder doesn't work

### ISSUE THREAD

**Issue by barteqcz** [veso266/SDRSharp.XDR#2]
SDR# crashes or the plugin just doesn't do anything after selecting external rds decoder.

**Comment by veso266** [comment]
oh hi there, sory for late reply (very busy theese days :cry: )

External RDS decoder was an attempt to improve RDS because SDR# RDS decoder was terrible compared to RDSSpy at the time

it worked with an rdsspy plugin I made (this would be an UDP Server which RDSSpy plugin would connect to to send rds data to) years ago: https://github.com/veso266/RDS-Spy-Plugins

sadly I wasn't able to extraxt PI code reliably from RDSSpy so this never worked properly (it did work, iirc but it was as usefull as RDS decoder from SDR#, it didn't extraxt PI code if it didn't receive complete group)

**Comment by barteqcz** [comment]
hi! thanks for your reply! i didn't know about your second plugin, though. i'm actually using your plugin with [FM-DX Webserver written by Noobish](https://github.com/NoobishSVK/fm-dx-webserver). it's meant to work with TEFs, or modified XDRs, but with your plugin i can also run it with RTL-SDR. the only problematic thing is the RDS decoding, since as you mentioned - RDS decoding in SDR# is completely terrible. the second thing is that i have to run windows since SDR# is windows-only, and that i have to emulate the COM port to point the plugin and [xdrd](https://github.com/kkonradpl/xdrd) to it. however, i wouldn't even get it to work without your work!
